name: flutter_sans
description: A simple Flutter App using Open Sans.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    # Official Google Font Open Sans shows U+2010 way too low (looks similar to underscore _):
    # https://github.com/google/fonts/issues/2460
    - family: OpenSansGoogleFonts
      fonts:
        - asset: assets/GoogleFonts/OpenSans-Regular.ttf
        - asset: assets/GoogleFonts/OpenSans-Bold.ttf
    # This version of Open Sans was built manually from the GitHub repo:
    # https://github.com/googlefonts/opensans
    # The problem with U+2010 seems to be fixed here:
    - family: OpenSansGithub
      fonts:
        - asset: assets/GitHub/OpenSans-Regular.ttf
        - asset: assets/GitHub/OpenSans-Bold.ttf
